# Generated by Django 4.2.5 on 2023-09-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.CharField(max_length=200)),
                ('rep_first_name', models.CharField(max_length=200)),
                ('rep_last_name', models.CharField(max_length=200)),
                ('rep_phone', models.CharField(max_length=200)),
                ('rep_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_number', models.CharField(max_length=200)),
                ('rep_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_rep', models.BooleanField()),
                ('is_isr', models.BooleanField()),
                ('phone', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wso_id', models.IntegerField()),
                ('meeting_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip', models.IntegerField()),
                ('location_details', models.CharField(max_length=200)),
                ('zoom_login', models.IntegerField()),
                ('zoom_pass', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.district')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.day')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.type'),
        ),
        migrations.CreateModel(
            name='GroupRepMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_group', models.BooleanField()),
                ('group_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.grouprep')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereandwhenapi.meeting')),
            ],
        ),
    ]
