# Generated by Django 4.2.5 on 2023-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereandwhenapi', '0002_alter_meeting_zoom_login_alter_meeting_zoom_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
