# Generated by Django 4.2.5 on 2023-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereandwhenapi', '0003_alter_meeting_email_alter_meeting_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
