# Generated by Django 4.2.5 on 2023-09-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whereandwhenapi', '0004_alter_meeting_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='type_name',
        ),
    ]
